<?php
$accentColor = $this->themeSetting('accent_color');
$navColor = $this->themeSetting('nav_color');
?>

<style>
    :root {
        <?php if ($accentColor): ?>
        --accent-color: <?php echo $accentColor; ?>;
        <?php endif; ?>

        <?php if ($navColor): ?>
        --nav-color: <?php echo $navColor; ?>;
        <?php endif; ?>
    }

    .banner {
        height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
        align-items: <?php echo $bannerPosition; ?>;
    }
    <?php if ($bannerHeightMobile !== ''): ?>
        @media screen and (max-width:640px) {
            .banner {
                height: <?php echo $bannerHeightMobile; ?>;
            }
        }
    <?php endif; ?>
</style>
