<?php
$accentColor = $this->themeSetting('accent_color');
$navColor = $this->themeSetting('nav_color');
?>

<?php if ($accentColor !== '' || $navColor !== ''): ?>
<style>
    <?php if ($accentColor): ?>
    a {
        color: <?php echo $accentColor; ?>
    }

    input[type="submit"]:hover,
    button:hover,
    .button:hover,
    .sub-menu a:hover,
    .site-page-pagination a:hover,
    a.advanced-search:hover {
        background-color: <?php echo $accentColor; ?>
    }

    button.slick-arrow span:before {
        color: <?php echo $accentColor; ?>
    }
    <?php endif; ?>

    <?php if ($navColor): ?>
    .oc-menu {
        background-color: <?php echo $navColor; ?>
    }
    <?php endif; ?>

    .banner {
        height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
        align-items: <?php echo $bannerPosition; ?>;
    }
    <?php if ($bannerHeightMobile !== ''): ?>
        @media screen and (max-width:640px) {
            .banner {
                height: <?php echo $bannerHeightMobile; ?>;
            }
        }
    <?php endif; ?>
</style>
<?php endif; ?>
