<?php
$accentColor = $this->themeSetting('accent_color');
$navColor = $this->themeSetting('nav_color');
?>

<style>
    <?php if ($accentColor || $navColor): ?>
    :root {
        <?php if ($accentColor): ?>
        --accent-color: <?php echo $accentColor; ?>;
        <?php endif; ?>

        <?php if ($navColor): ?>
        --nav-color: <?php echo $navColor; ?>;
        <?php endif; ?>
    }
    <?php endif; ?>

    .banner {
        height: <?php echo (isset($bannerHeight) && $bannerHeight !== '') ? $bannerHeight : 'auto'; ?>;
        align-items: <?php echo (isset($bannerPosition) && $bannerPosition !== '') ? $bannerPosition : 'center'; ?>;
    }
    <?php if (isset($bannerHeight) && $bannerHeightMobile !== ''): ?>
        @media screen and (max-width:640px) {
            .banner {
                height: <?php echo $bannerHeightMobile; ?>;
            }
        }
    <?php endif; ?>
</style>
