  <?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/mmenu.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic%7CBitter:700');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/mmenu.js'));
$this->headScript()->appendFile($this->assetUrl('js/mmenu-init.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$this->jsTranslate();
$userBar = $this->userBar();
$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$bodyTruncate = ($this->themeSetting('truncate_body_property') ? $this->themeSetting('truncate_body_property') : 'full'); 
$this->htmlElement('body')->appendAttribute('class', 'body-truncate-' . $bodyTruncate);
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php 
        echo $this->partial('common/theme-setting-css', [
            'bannerHeight' => $bannerHeight,
            'bannerHeightMobile' => $bannerHeightMobile,
            'bannerPosition' => $bannerPosition
        ]); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <div id="oc-container" class="oc-container">
            <div class="oc-pusher">
                <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
                <?php echo $userBar; ?>
                <header>
                    <h1>
                        <a href="<?php echo $site->url(); ?>" class="site-title">
                        <?php if ($this->themeSetting('logo')): ?>
                            <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                        <?php else: ?>
                            <?php echo $escape($siteTitle); ?>
                        <?php endif; ?>
                        </a>
                    </h1>
                    <?php echo $this->partial('common/search-form'); ?>
                    <div id="oc-trigger">
                        <a href="#menu" role="button" id="menu-button" class="button" data-effect="oc-push" title="<?php echo $this->translate('Menu'); ?>"><span class="sr-only"><?php echo $this->translate('Menu'); ?></span><span class="icon" aria-hidden="true"></span></a>
                    </div>
                    <nav id="menu" class="oc-menu oc-push">
                        <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                    </nav>
                </header>

                <div class="oc-content">
                  <div class="oc-content-inner">
                    <?php if ($banner): ?>
                    <div class="banner <?php echo $bannerWidth; ?>">
                        <img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
                    </div>
                    <?php endif; ?>
                    <div id="content" role="main">
                      <?php echo $this->content; ?>
                    </div>
                    <footer>
                        <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                        <?php else: ?>
                            <?php echo $this->translate('Powered by Omeka S'); ?>
                        <?php endif; ?>
                    </footer>
                  </div>
                </div>
            </div>
        </div>
    </body>
</html>
